version: "3"

services:
  django:
    build:
      context: ./sql-joe-backend
      dockerfile: Dockerfile
    volumes:
      - django_static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./sql-joe-backend/.env
    # This does not look this the correct comand?????
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - django_static_volume:/usr/src/app/django_files/static
    ports:
      - 80:80

volumes:
  postgres_data:
  django_static_volume:
