# Generated by Django 3.2.5 on 2021-07-04 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_remotedatabaseconnections_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedatabaseconnections',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
